[package]
name = "bevy-in-web-worker"
description = "bevy +  web worker"
authors = ["Jinlei Li"]
version = "0.1.0"
edition = "2021"
rust-version = "1.78"

[lib]
crate-type = ["cdylib"]

[dependencies]
raw-window-handle = "0.6.2"
wgpu = "0.20"
#bevy = { git = "https://github.com/bevyengine/bevy", rev = "104dcf5a6732ad8c77c22d098a2fe300e7c5c377", features = [
bevy = { version = "0.14", features = [
    "bevy_pbr",
    # "bevy_ui",
    # "bevy_sprite",
    "bevy_gizmos",
    # "ktx2",
    "tonemapping_luts",
    "webgpu",
], default-features = false }
uuid = { version = "1.7.0", features = ["v4"] }
rand = "0.8"
# Web only
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
web-sys = { version = "0.3.67", features = [
    "Window",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "OffscreenCanvas",
    "MouseEvent",
    "Worker",
    "DedicatedWorkerGlobalScope",
    "Event",
    "MessageEvent",
    "Blob",
    "BlobPropertyBag",
    "Url",
] }
js-sys = "0.3.69"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = "fat"
# lto = true
codegen-units = 1
